# Generated by Django 5.2.3 on 2025-11-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upadate_date',
            new_name='update_date',
        ),
    ]
