# Generated by Django 5.2.3 on 2025-11-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_upadate_date_post_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/o3.jpg', upload_to='upload'),
        ),
    ]
