# Generated by Django 5.2.3 on 2025-11-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='o3.jpg', upload_to='img/upload'),
        ),
    ]
