# Generated by Django 5.2.3 on 2026-04-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_contact_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
